In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# 1.Load the kinematics dataset as measured on mobile sensors from the file “run_or_walk.csv”. List out the columns in the dataset.

In [9]:
df=pd.read_csv('c:/edureka/run_or_walk.csv')
df.head()

date                time username  wrist  activity  acceleration_x  \
0  2017-6-30  13:51:15:847724020   viktor      0         0          0.2650   
1  2017-6-30  13:51:16:246945023   viktor      0         0          0.6722   
2  2017-6-30  13:51:16:446233987   viktor      0         0          0.4399   
3  2017-6-30  13:51:16:646117985   viktor      0         0          0.3031   
4  2017-6-30  13:51:16:846738994   viktor      0         0          0.4814   

   acceleration_y  acceleration_z  gyro_x  gyro_y  gyro_z  
0         -0.7814         -0.0076 -0.0590  0.0325 -2.9296  
1         -1.1233         -0.2344 -0.1757  0.0208  0.1269  
2         -1.4817          0.0722 -0.9105  0.1063 -2.4367  
3         -0.8125          0.0888  0.1199 -0.4099 -2.9336  
4         -0.9312          0.0359  0.0527  0.4379  2.4922

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88588 entries, 0 to 88587
Data columns (total 11 columns):
date              88588 non-null object
time              88588 non-null object
username          88588 non-null object
wrist             88588 non-null int64
activity          88588 non-null int64
acceleration_x    88588 non-null float64
acceleration_y    88588 non-null float64
acceleration_z    88588 non-null float64
gyro_x            88588 non-null float64
gyro_y            88588 non-null float64
gyro_z            88588 non-null float64
dtypes: float64(6), int64(2), object(3)
memory usage: 7.4+ MB


In [11]:
df.columns

Index(['date', 'time', 'username', 'wrist', 'activity', 'acceleration_x',
       'acceleration_y', 'acceleration_z', 'gyro_x', 'gyro_y', 'gyro_z'],
      dtype='object')

In [12]:
df.isnull().sum()

date              0
time              0
username          0
wrist             0
activity          0
acceleration_x    0
acceleration_y    0
acceleration_z    0
gyro_x            0
gyro_y            0
gyro_z            0
dtype: int64

In [6]:
df.shape

(88588, 11)

# Convert Date and Time Column to datetime and merge it 

In [13]:
df.date = pd.to_datetime(df.date)
df.time = np.array([a[::-1].replace(":",".",1)[::-1] for a in df.time.values], dtype=object)
df.time = pd.to_timedelta(df.time)
df.date += df.time
df = df.drop("time", axis=1)

# Drop username which doesn't have any significance while prediction

In [14]:
df.drop(['username'],axis=1,inplace=True)


In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88588 entries, 0 to 88587
Data columns (total 9 columns):
date              88588 non-null datetime64[ns]
wrist             88588 non-null int64
activity          88588 non-null int64
acceleration_x    88588 non-null float64
acceleration_y    88588 non-null float64
acceleration_z    88588 non-null float64
gyro_x            88588 non-null float64
gyro_y            88588 non-null float64
gyro_z            88588 non-null float64
dtypes: datetime64[ns](1), float64(6), int64(2)
memory usage: 6.1 MB


# Set Date as index

In [18]:
df.set_index("date", inplace=True)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 88588 entries, 2017-06-30 13:51:15.847724020 to 2017-07-09 20:09:16.117410004
Data columns (total 8 columns):
wrist             88588 non-null int64
activity          88588 non-null int64
acceleration_x    88588 non-null float64
acceleration_y    88588 non-null float64
acceleration_z    88588 non-null float64
gyro_x            88588 non-null float64
gyro_y            88588 non-null float64
gyro_z            88588 non-null float64
dtypes: float64(6), int64(2)
memory usage: 6.1 MB


# 2. Let the target variable ‘y’ be the activity and assign all the columns after it to ‘x’.

# Prepare Data

In [20]:
X=df.drop(['activity'],axis=1)
y=df['activity']

# Split train and test data

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=1)

# 3.Using Scikit-learn fit a Gaussian Naive Bayes model and observe the accuracy. Generate a classification report using scikit learn.

In [16]:
from sklearn.naive_bayes import GaussianNB
gausmodel=GaussianNB()
gausmodel.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [17]:
y_pred=gausmodel.predict(X_test)

In [18]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(accuracy_score(y_test,y_pred)*100)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

95.60616322384016
[[17355   195]
 [ 1362 16524]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96     17550
           1       0.99      0.92      0.96     17886

   micro avg       0.96      0.96      0.96     35436
   macro avg       0.96      0.96      0.96     35436
weighted avg       0.96      0.96      0.96     35436



In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 88588 entries, 2017-06-30 13:51:15.847724020 to 2017-07-09 20:09:16.117410004
Data columns (total 8 columns):
wrist             88588 non-null int64
activity          88588 non-null int64
acceleration_x    88588 non-null float64
acceleration_y    88588 non-null float64
acceleration_z    88588 non-null float64
gyro_x            88588 non-null float64
gyro_y            88588 non-null float64
gyro_z            88588 non-null float64
dtypes: float64(6), int64(2)
memory usage: 6.1 MB


In [22]:
df.columns

Index(['wrist', 'activity', 'acceleration_x', 'acceleration_y',
       'acceleration_z', 'gyro_x', 'gyro_y', 'gyro_z'],
      dtype='object')

# 4.Repeat the model once using only the acceleration values as predictors and then using only the gyro values as predictors. Comment on the difference in accuracy between both the models.

In [23]:
X=df[['acceleration_x','acceleration_y','acceleration_z']]
y=df['activity']

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [26]:
from sklearn.naive_bayes import GaussianNB
gausmodel=GaussianNB()
gausmodel.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [27]:
y_pred=gausmodel.predict(X_test)

In [28]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(accuracy_score(y_test,y_pred)*100)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

95.65978101365843
[[8610   63]
 [ 706 8339]]
              precision    recall  f1-score   support

           0       0.92      0.99      0.96      8673
           1       0.99      0.92      0.96      9045

   micro avg       0.96      0.96      0.96     17718
   macro avg       0.96      0.96      0.96     17718
weighted avg       0.96      0.96      0.96     17718



In [29]:
X=df[['gyro_x', 'gyro_y', 'gyro_z']]
y=df['activity']

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [31]:
from sklearn.naive_bayes import GaussianNB
gausmodel=GaussianNB()
gausmodel.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [32]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(accuracy_score(y_test,y_pred)*100)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

95.65978101365843
[[8610   63]
 [ 706 8339]]
              precision    recall  f1-score   support

           0       0.92      0.99      0.96      8673
           1       0.99      0.92      0.96      9045

   micro avg       0.96      0.96      0.96     17718
   macro avg       0.96      0.96      0.96     17718
weighted avg       0.96      0.96      0.96     17718



Accuracy is same when predicting with either acceleration values as predictors or gyro values as predictors.