In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# 1.We shall use the same dataset used in previous assignment - digits. Make a 80-20 train/test split.

In [2]:
from sklearn.datasets import load_digits
digits=load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [4]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [6]:
images= digits.images
target=digits.target
images.shape,target.shape

((1797, 8, 8), (1797,))

# Reshape Images

In [7]:
images=images.reshape((images.shape[0],-1))
images.shape

(1797, 64)

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(images,target,test_size=0.2,random_state=1)

In [9]:
X_train.shape,y_train.shape

((1437, 64), (1437,))

In [10]:
X_test.shape,y_test.shape

((360, 64), (360,))

# 2.Using scikit learn perform a LDA on the dataset. Find out the number of components in the projected subspace.

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components = 2)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


# 3.Transform the dataset and fit a logistic regression and observe the accuracy. Compare it with the previous model based on PCA in terms of accuracy and model complexity.

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
 
# Predicting the Test set results
y_pred = classifier.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [14]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[41  0  0  0  0  0  2  0  0  0]
 [ 0 29  0  0  0  0  1  3  2  0]
 [ 0  2 27  5  0  0  0  0  0  2]
 [ 0  0  2 33  0  0  0  0  0  6]
 [ 1  0  0  0 37  0  0  0  0  0]
 [ 1  0  0  3  0 20  3  0  1  2]
 [ 1  0  0  0  6  0 30  0  0  0]
 [ 0  9  0  0  1  1  1 11 14  0]
 [ 0  2  2  0  0  1  0  5 14  5]
 [ 0  0  0  3  0 18  1  0  5  7]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94        43
           1       0.69      0.83      0.75        35
           2       0.87      0.75      0.81        36
           3       0.75      0.80      0.78        41
           4       0.84      0.97      0.90        38
           5       0.50      0.67      0.57        30
           6       0.79      0.81      0.80        37
           7       0.58      0.30      0.39        37
           8       0.39      0.48      0.43        29
           9       0.32      0.21      0.25        34

   micro avg       0.69      0.69      0.69       360
   macro avg       

In [15]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.6916666666666667
